<?php
/**
 * @file
 * @copyright Copyright (c) 2014 Palantir.net
 */


/**
 * Implements hook_preprocess_node().
 */
function ceo_certification_accreditation_preprocess_node(&$variables) {
  global $user;

  if ($user->uid != 0) {
    if (empty($variables['course_term'])) {
      $variables['course_term'] = taxonomy_get_term_by_name($variables['title']);
    }
    if (!empty($variables['course_term']) && empty($variables['credits_obtained'])) {
      foreach ($variables['course_term'] as $value) {
        $query = db_select('ceo_certification_accreditation', 'ca')
          ->fields('ca', array('credits'))
          ->condition('ca.uid', $user->uid)
          ->condition('ca.cid', $value->tid);
        $results = $query->execute()->fetchAll();
        if (!empty($results)) {
          $credits_obtained = 0;
          foreach ($results as $value) {
            $credits_obtained += $value->credits;
          }

        }
        $variables['credits_obtained'] = $credits_obtained;
      }
    }
  }

}
