<?php

/**
 * @file
 * Install, update, and uninstall functions for th wistia module.
 */

/**
 * Implements hook_field_schema().
 */
function wistia_field_schema($field) {
  $schema = NULL;

  $schema = array(
    'columns' => array(
      'wistia' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
      ),
    ),
    'indexes' => array(
      'wistia' => array('wistia'),
    ),
  );

  return $schema;
}