<?php

/**
 * @file
 * Integrates Wistia oembed fields with the Wistia player API.
 *
 * @copyright (c) Copyright 2014 Spyder Byte Design LLC
 */

function ceo_wistia_menu() {
  $items['ceo_wistia/progress'] = array(
    'title' => 'Title',
    'description' => 'Description',
    'access callback' => 'user_access',
    'access arguments' => array('ceo_wistia'),
    'page callback' => 'ceo_wistia_foo_page',
    'page arguments' => array(),
    'type' => MENU_CALLBACK,
  );
}

/**
 * Implements hook_preprocess_field().
 */
function ceo_wistia_preprocess_field(&$variables, $hook) {
  // Add javascript for Wistia javascript Player API.
  if($variables['element']['#field_name'] == 'field_video') {

    global $user;

    $my_settings =  array(
      'uid' => $user->uid,
      'nid' => $variables['element']['#object']->nid,
    );
    drupal_add_library('system', 'ui.dialog');
    drupal_add_js(drupal_get_path('module', 'ceo_wistia') . '/ceo_wistia.js', array('scope' => 'footer'));
    drupal_add_js(array('ceo_wistia' => $my_settings), 'setting');
  }
}